name: François Cabrol
author: François Cabrol
accroche: "#Java-Scala-Javascript programming #Human-machine interface #Computermusic #Information visualization"
mail: francois.cabrol@live.ca
markdown: kramdown
safe: false
lsi: false
highlighter: pygments
permalink: none
exclude: [README.md, Rakefile]
gems:
  - jekyll-sitemap
